### ISSUE TITLE
TypeError - when launching

### ISSUE THREAD

**Issue by nikolastjepanovic** [1103s/crypto-bot#1]
`TypeError: predict_next_N_timesteps() takes 2 positional arguments but 4 were given
`

**Comment by epelofske-student** [comment]
@nniks19 Can you a larger code snippet where this error was encountered? For example was this when calling `crypto_util.py`?

**Comment by epelofske-student** [comment]
@nniks19 Thank you for the bug report! We have fixed this particular issue for the command line interface in a recent commit https://github.com/1103s/crypto-bot/commit/ec9a28f97f84b3c3884266daf47dd3648e772b40

Please re-open the issue if the error persists.
